version: '2.1'

orbs:
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.18

executors:
  jdk17:
    docker:
      - image: cimg/openjdk:17.0

workflows:
  main:
    jobs:
      - circleci-maven-release-orb/run-maven-release:
          executor:
            name: jdk17
          mvn-release-perform-command: >-
            mvn --batch-mode release:perform -DdryRun=true -s .circleci/.maven.xml
          ssh-fingerprints: 'c1:84:0c:41:8a:1c:43:ba:a5:31:40:bb:32:8b:36:0c'