version: '2.1'

orbs:
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.18

executors:
  jdk17:
    docker:
      - image: cimg/openjdk:17.0

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            mvn test
            curl https://deepsource.io/cli | sh
            ./bin/deepsource report --analyzer test-coverage --key javascript --value-file target/site/jacoco/jacoco.xml
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r target/site/jacoco/jacoco.xml

workflows:
  main:
    jobs:
      - test
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
          executor:
            name: jdk17
          mvn-release-perform-command: >-
            mvn --batch-mode release:perform -DdryRun=true -s .circleci/.maven.xml
          ssh-fingerprints: 'c1:84:0c:41:8a:1c:43:ba:a5:31:40:bb:32:8b:36:0c'